services:
  leaderboard.api:
    image: leaderboard.api
    build:
      context: .
      dockerfile: Leaderboard.Api/Dockerfile
    container_name: leaderboard-api
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - "8080:8080"
    environment:
      AppStartupSettings__CorsAllowedOrigins__0: ${FRONTEND_URL:-http://localhost:5173}
      ConnectionStrings__PostgresSQL: Server=postgres;Port=5432;Database=leaderboard;User Id=postgres;Password=${POSTGRES_PASSWORD}
      JwtSettings__SigningKey: ${JWT_SIGNING_KEY}
      RedisSettings__Host: redis
      RedisSettings__Password: ${REDIS_PASSWORD}

  postgres:
    image: postgres:17
    container_name: leaderboard-postgres
    ports:
      - "15432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: leaderboard
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d leaderboard" ]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: leaderboard-redis
    ports:
      - "6379:6379"
    command: [ "redis-server", "--requirepass", "${REDIS_PASSWORD}", "--maxmemory-policy", "volatile-lru" ]
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
