using Leaderboard.DAL;
using Leaderboard.Domain.Entities;
using Leaderboard.Tests.TestData;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;

namespace Leaderboard.Tests.FunctionalTests.Configurations;

internal static class PrepDb
{
    public static void PrepPopulation(this IServiceScope serviceScope)
    {
        var dbContext = serviceScope.ServiceProvider.GetRequiredService<ApplicationDbContext>();

        dbContext.Database.EnsureDeleted();
        dbContext.Database.Migrate();

        // The first owner comes from the migration seed, so it is updated, not inserted
        var owners = OwnerMother.GetOwners().ToList();
        var seededOwner = dbContext.Set<LeaderboardOwner>().Single(x => x.Id == 1);
        seededOwner.Login = owners[0].Login;
        seededOwner.PasswordHash = owners[0].PasswordHash;
        seededOwner.FirstName = owners[0].FirstName;
        seededOwner.LastName = owners[0].LastName;

        // Ids are generated by the database in insertion order, so they match the mothers
        var otherOwners = owners.Skip(1).ToList();
        var years = AcademicYearMother.GetAcademicYears().ToList();
        var classes = ClassMother.GetClasses().ToList();
        var students = StudentMother.GetStudents().ToList();
        var transactions = ScoreTransactionMother.GetScoreTransactions().ToList();
        var refreshTokens = RefreshTokenMother.GetRefreshTokens().ToList();

        otherOwners.ForEach(x => x.Id = 0);
        years.ForEach(x => x.Id = 0);
        classes.ForEach(x => x.Id = 0);
        students.ForEach(x => x.Id = 0);
        transactions.ForEach(x => x.Id = 0);
        refreshTokens.ForEach(x => x.Id = 0);

        dbContext.Set<LeaderboardOwner>().AddRange(otherOwners);
        dbContext.Set<AcademicYear>().AddRange(years);
        dbContext.Set<SchoolClass>().AddRange(classes);
        dbContext.SaveChanges();

        dbContext.Set<Student>().AddRange(students);
        dbContext.Set<RefreshToken>().AddRange(refreshTokens);
        dbContext.SaveChanges();

        dbContext.Set<ScoreTransaction>().AddRange(transactions);
        dbContext.SaveChanges();
    }
}